from autogen_agentchat.agents import AssistantAgent, CodeExecutorAgent
from autogen_ext.models.openai import OpenAIChatCompletionClient
from autogen_agentchat.teams import RoundRobinGroupChat
from autogen_agentchat.ui import Console
from autogen_ext.code_executors.local import LocalCommandLineCodeExecutor
from dotenv import load_dotenv
import asyncio
import os

load_dotenv()

llm = OpenAIChatCompletionClient(
    model="gpt-4o-mini"
)

workspace = os.path.abspath("my_workspace")

# Coder Agent
coder = AssistantAgent(
    name="coder",
    model_client=llm,
    system_message=f"""
    You are an expert python coder. Your workspace is {workspace}.
    1. Always write code in 'python' markdown blocks.
    2. When creating data, explictly save it to a file (CSV, TXT etc.)
    3. If the executor returns an error, fix it.
    """,
    model_client_stream=True
)

# Code Executor Agent
executor = LocalCommandLineCodeExecutor(work_dir=workspace)
executor_agent = CodeExecutorAgent(
    name="executor_agent",
    code_executor=executor
)

# def upload_file():
#     pass

# uploader_agent = AssistantAgent(
#     name="uploader_agent",
#     model_client=llm,
#     system_message="You are a file uploader agent who uploads the file generated by executor_agent presnet in workspace {}. You use the tool to upload file.",
#     tools=[upload_file]
# )


team = RoundRobinGroupChat(
    participants=[coder, executor_agent],
    max_turns=2
)

async def main():
    await Console(team.run_stream(task="Create a CSV file name users.csv with 5 rows of dummy user data (name, email)"))

asyncio.run(main())